pipeline:
  name: ec2-demo
  identifier: ec2demo
  projectIdentifier: testharness
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: terraform-ec2
        identifier: terraformec2
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: Terraform Init
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
